<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:tps="http://www.dkateros.gr/ws/echo" 
	xmlns:tns="http://www.dkateros.gr/ws"
	targetNamespace="http://www.dkateros.gr/ws">

	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.dkateros.gr/ws/echo" schemaLocation="echo.xsd" />
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="EchoRequest">
		<wsdl:part name="EchoInput" element="tps:EchoInput" />
	</wsdl:message>

	<wsdl:message name="EchoResponse">
		<wsdl:part name="EchoOutput" element="tps:EchoOutput" />
	</wsdl:message>

	<wsdl:portType name="EchoPortType">
		<wsdl:operation name="Echo">
			<wsdl:input message="tns:EchoRequest" name="EchoRequest" />
			<wsdl:output message="tns:EchoResponse" name="EchoResponse" />
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="EchoBinding" type="tns:EchoPortType">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
		<wsdl:operation name="Echo">
			<soap:operation soapAction="Echo" />
			<wsdl:input name="EchoRequest">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="EchoResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="EchoService">
		<wsdl:port binding="tns:EchoBinding" name="EchoPort">
			<soap:address location="REPLACE_WITH_ACTUAL_URL" />
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>